In [13]:
import numpy as np
import pandas as pd

### Import first dataset

In [2]:
species = pd.read_csv('./species_info.csv')
species.head()

,category,scientific_name,common_names,conservation_status
0,Mammal,Clethrionomys gapperi gapperi,Gapper's Red-Backed Vole,NaN
1,Mammal,Bos bison,"American Bison, Bison",NaN
2,Mammal,Bos taurus,"Aurochs, Aurochs, Domestic Cattle (Feral), Dom...",NaN
3,Mammal,Ovis aries,"Domestic Sheep, Mouflon, Red Sheep, Sheep (Feral)",NaN
4,Mammal,Cervus elaphus,Wapiti Or Elk,NaN

In [3]:
species.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 5824 entries, 0 to 5823
Data columns (total 4 columns):
 #   Column               Non-Null Count  Dtype
---  ------               --------------  -----
 0   category             5824 non-null   object
 1   scientific_name      5824 non-null   object
 2   common_names         5824 non-null   object
 3   conservation_status  191 non-null    object
dtypes: object(4)
memory usage: 182.1+ KB

# Null values

In [4]:
species.isnull().sum()/len(species)

category               0.000000
scientific_name        0.000000
common_names           0.000000
conservation_status    0.967205
dtype: float64

In [5]:
species['conservation_status'].unique()

array([nan, 'Species of Concern', 'Endangered', 'Threatened',
       'In Recovery'], dtype=object)

After sampling a few records classified as `NaN`, it can be concluded that these missing values represent species with a **Least Concern** conservation status. Therefore, `NaN` values in this column will be replaced with `"Least Concern"` using `fillna()`.

In [6]:
species['conservation_status'] = species['conservation_status'].fillna('Least Concern')

In [7]:
species.isna().sum()

category               0
scientific_name        0
common_names           0
conservation_status    0
dtype: int64

# Duplicates

In [8]:
species.duplicated().sum()

np.int64(0)

No duplicates have been found in this dataset

In [9]:
species.describe(include='all').T

                    count unique                   top  freq
category             5824      7        Vascular Plant  4470
scientific_name      5824   5541  Hypochaeris radicata     3
common_names         5824   5504    Brachythecium Moss     7
conservation_status  5824      5         Least Concern  5633

In [10]:
species.sample(10)

,category,scientific_name,common_names,conservation_status
5431,Vascular Plant,Gayophytum heterozygum,"Dwarf Groundsmoke, Zigzag Groundsmoke",Least Concern
4536,Bird,Zonotrichia leucophrys oriantha,Mountain White-Crowned Sparrow,Least Concern
5715,Vascular Plant,Cercocarpus betuloides var. betuloides,Birch-Leaf Mountain-Mahogany,Least Concern
2622,Vascular Plant,Fothergilla major,"Mountain Witchalder, Mountain Witch-Alder",Least Concern
3871,Vascular Plant,Trifolium repens,"Dutch Clover, Ladino Clover, White Clover, Whi...",Least Concern
4980,Vascular Plant,Pseudostellaria jamesiana,"Sticky Starwort, Sticky-Starwort, Tuber Starwort",Least Concern
895,Vascular Plant,Prenanthes altissima,"Tall Rattlesnakeroot, Tall Rattlesnake-Root",Least Concern
3880,Vascular Plant,Asclepias speciosa,Showy Milkweed,Least Concern
1066,Vascular Plant,Buxus sempervirens,"Boxwood, Common Boxwood",Least Concern
3801,Vascular Plant,Kalmia microphylla,"Alpine Bog Laurel, Alpine Laurel",Least Concern

### Import second dataset

In [11]:
observations = pd.read_csv('./observations.csv')
observations.head()

            scientific_name                            park_name  observations
0        Vicia benghalensis  Great Smoky Mountains National Park            68
1            Neovison vison  Great Smoky Mountains National Park            77
2         Prunus subcordata               Yosemite National Park           138
3      Abutilon theophrasti                  Bryce National Park            84
4  Githopsis specularioides  Great Smoky Mountains National Park            85

In [12]:
observations.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 23296 entries, 0 to 23295
Data columns (total 3 columns):
 #   Column           Non-Null Count  Dtype
---  ------           --------------  -----
 0   scientific_name  23296 non-null  object
 1   park_name        23296 non-null  object
 2   observations     23296 non-null  int64
dtypes: int64(1), object(2)
memory usage: 546.1+ KB